### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by 4external** [ya-erm/money-keeper#75]
Здравствуйте!

Скажите, пожалуйста, какие есть идеи для версии 3.0? 

Дело в том, что использую ваш проект в качестве примера для обучения sveltekit в pwa. И интересует, что будет в 3.0 - больше фич или что-то глобальное , типа смены стека, библиотек и т.п.

**Comment by ya-erm** [comment]
Добрый день!

Версии 3.0 пока нет в планах. Мажорная версия будет подниматься с 2 на 3 только если будут какие-то глобальные изменения, несовместимые с текущей версией. Например, версия 1 была без возможности работы приложения в оффлайн режиме, в версии 2, чтобы это исправить, была значительно изменена структура базы данных, методы сохранения и синхронизации с сервером.

Стек существенно менять тоже не планирую пока. Проект точно останется на `svelte` и `ts`, а внешние библиотеки могут быть заменены, если чем-то не устроят, или если найдутся более привлекательные варианты. Например, думаю отказаться от `eslint` в пользу `biome`, когда там появится полноценная поддержка синтаксиса svelte. Или, например библиотека `dayjs` может быть будет заменена на `date-fns`
